name: Publish gh-pages
on:
  push:
    branches:
      - master

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set-up Node
        uses: actions/setup-node@v1
        with:
          node-version: "10.x"
      - run: git config --global user.email "gupta.shivam1490@gmail.com"
      - run: git config --global user.name "Shivam Gupta"
      - run: npm install
      - run: npm run deploy
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_SECRET_TOKEN }}
